#!/usr/bin/env python3

import sys
from sympy import factorint

def factorize_numbers(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorint(number)
            print(f"{number}={factors}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    factorize_numbers(filename)
