#!/usr/bin/env python3

import sys
from sympy import isprime, factorint

def factorize_rsa_number(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            p, q = find_primes(number)
            print(f"{number}={p}*{q}")

def find_primes(n):
    for i in range(2, n):
        if isprime(i) and n % i == 0:
            return i, n // i

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./rsa <file>")
        sys.exit(1)

    filename = sys.argv[1]
    factorize_rsa_number(filename)
